### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by xpackal5** [contributte/logging#29]
After setup extension does not work
```
bin/console
Nette\InvalidStateException: Name already has been set. in /var/www/html/vendor/nette/di/src/DI/Definitions/Definition.php:45
Stack trace:
#0 /var/www/html/vendor/nette/di/src/DI/ContainerBuilder.php(84): Nette\DI\Definitions\Definition->setName('logging.origina...')
#1 /var/www/html/vendor/contributte/logging/src/DI/TracyLoggingExtension.php(40): Nette\DI\ContainerBuilder->addDefinition('logging.origina...', Object(Nette\DI\Definitions\ServiceDefinition))
#2 /var/www/html/vendor/nette/di/src/DI/Compiler.php(232): Contributte\Logging\DI\TracyLoggingExtension->loadConfiguration()
#3 /var/www/html/vendor/nette/di/src/DI/Compiler.php(207): Nette\DI\Compiler->processExtensions()
#4 /var/www/html/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\DI\Compiler->compile()
#5 /var/www/html/vendor/nette/di/src/DI/ContainerLoader.php(79): Nette\DI\ContainerLoader->generate('Container_53e17...', Array)
#6 /var/www/html/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile('Container_53e17...', Array)
#7 /var/www/html/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(242): Nette\DI\ContainerLoader->load(Array, Array)
#8 /var/www/html/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(221): Nette\Configurator->loadContainer()
#9 /var/www/html/bin/console(10): Nette\Configurator->createContainer()
#10 {main}
(stored in /var/www/html/app/../log/exception--2019-09-25--17-40--0dfcde7311.html)
```

composer.json
```
extensions:
    logging: Contributte\Logging\DI\TracyLoggingExtension

logging:
    logDir: %appDir%/../log
```

**Comment by f3l1x** [comment]
Hi @xpackal5, can you please provide more informations? PHP version, nette version, this package version etc.

**Comment by xpackal5** [comment]
PHP 7.3..
require part of my composer.json
```
        "squizlabs/php_codesniffer": "^3.4",
        "jakub-onderka/php-parallel-lint": "^1.0",
        "jakub-onderka/php-console-highlighter": "^0.4.0",
        "nette/application": "^3.0",
        "tracy/tracy": "2.5.8",
        "nette/di": "^3.0",
        "nette/tester": "^2.3",
        "nette/forms": "^3.0",
        "nette/mail": "^3.1",
        "nette/neon": "^3.0",
        "nette/security": "^3.0",
        "nette/tokenizer": "^3.1",
        "nette/bootstrap": "^3.0",
        "nette/caching": "^3.0",
        "nette/component-model": "^3.0",
        "nette/finder": "^2.5",
        "latte/latte": "^2.5",
        "nette/safe-stream": "^2.4",
        "nette/robot-loader": "^3.2",
        "nette/utils": "^3.0",
        "nette/http": "^3.0",
        "contributte/console": "^0.7.1",
        "friendsofphp/php-cs-fixer": "^2.15",
        "contributte/console-extra": "^0.5.0",
        "contributte/utils": "^0.4.1",
        "contributte/latte-parsedown-extra": "^1.5",
        "contributte/bootstrap": "^0.4.0",
        "contributte/http": "^0.3.0",
        "contributte/application": "^0.4.0",
        "nettrine/dbal": "^0.5.0",
        "nettrine/orm": "^0.4.0",
        "nettrine/migrations": "^0.6.0",
        "contributte/scheduler": "^0.5.0",
        "contributte/event-dispatcher": "^0.6.0",
        "contributte/cache": "^0.5.0",
        "oyejorge/less.php": "v1.7.0.14",
        "leafo/scssphp": "^0.8.4",
        "kdyby/translation": "^3.0",
        "dotblue/nette-pdf": "^3.2",
        "nettrine/hydrator": "^1.0",
        "nettrine/annotations": "^0.5.0",
        "contributte/recaptcha": "^3.2",
        "guzzlehttp/guzzle": "^6.3",
        "contributte/neonizer": "^0.4.0",
        "contributte/logging": "^0.3.0",
        "contributte/tracy": "0.3.1"
```

**Comment by f3l1x** [comment]
I must say I don't know where is the catch. :-(

**Comment by steinbauer** [comment]
I have same problem...

adding:
```
extensions:
	logging: Contributte\Logging\DI\TracyLoggingExtension

logging:
    logDir: %appDir%/../log
```

and problem begins to exist in `contributte/logging/src/DI/TracyLoggingExtension.php:40`

-----------------

`$name` is
`vendor/nette/di/src/DI/Definitions/Definition.php:45` - `$name = 'logging.originalLogger'`


------------
php8, "contributte/application": "^v0.5.0"
